name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'README.zh-CN.md'
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

# Add permissions needed for GitHub Container Registry
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,amd64'
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set lowercase owner name
        id: lowercase
        run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: List files in context
        run: ls -la

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ steps.lowercase.outputs.owner }}/finclip-agent:latest
            ghcr.io/${{ steps.lowercase.outputs.owner }}/finclip-agent:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
